[versions]
minecraft = "1.16.1"
yarn_mappings = "1.16.1-build.27"
fabric_loader = "0.16.2"
loom = "1.7-SNAPSHOT"
vineflower = "1.10.1"
speedrunapi = "v1.0.1"
worldpreview = "v6.0.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "dev.tildejustin:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
speedrunapi = { module = "com.github.kingcontaria:speedrunapi", version.ref = "speedrunapi" }
worldpreview = { module = "com.github.kingcontaria:mcsr-worldpreview-1.16.1", version.ref = "worldpreview" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
